java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
      secrets:
        - data-store-api-draftStoreEncryptionSecret
        - data-store-api-draft-key
        - ccd-data-s2s-secret
        - ccd-ELASTIC-SEARCH-URL
        - ccd-ELASTIC-SEARCH-DATA-NODES-URL
        - ccd-ELASTIC-SEARCH-PASSWORD
  environment:
    DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
    DATA_STORE_DB_MAX_POOL_SIZE: 10
    DEFINITION_STORE_HOST: http://ccd-definition-store-api-pr-619.service.core-compute-preview.internal/
#    USER_PROFILE_HOST: http://ccd-user-profile-api-pr-224.service.core-compute-preview.internal/

    ENABLE_DB_MIGRATE: true
    ELASTIC_SEARCH_ENABLED: true
    ELASTIC_SEARCH_NODES_DISCOVERY_ENABLED: true
  postgresql:
    enabled: true

elastic:
  enabled: true

elasticsearch:
  nameOverride: es
  cluster:
    env: {MINIMUM_MASTER_NODES: "1"}
  master:
    replicas: 1
    persistence:
      enabled: false
  client:
    replicas: 1
    persistence:
      enabled: false
  data:
    replicas: 1
    persistence:
      enabled: false

logstash:
  image:
    repository: hmcts/ccd-logstash
    tag: latest
    pullPolicy: IfNotPresent
  logstashJavaOpts: -Xmx1g -Xms512M
  persistence:
    enabled: false
  elasticsearch:
    host: "{{ .Release.Name }}-es-client"
    port: 9200
  configTpl:
    xpack.monitoring.enabled: "false"
    db.url: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/javadatabase?stringtype=unspecified"
    db.user: "javapostgres"
    db.pwd: "javapassword"
    es.data.nodes.url: "http://{{ .Release.Name }}-es-master:9200"
