name: Example CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  COMMENT_ID: diffblue-test-result-comment-${{github.base_ref}}-${{github.head_ref}}

jobs:
  security:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Update comment on PR
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        with:
          message: "Diffblue is analysing your PR for security vulnerabilities"
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

      - name: Setup git
        run: |
          git fetch origin
          git checkout ${{ github.head_ref }}
          git config --global user.email "db-ci-platform@diffblue.com"
          git config --global user.name "Diffblue CI"

      # # Initializes the CodeQL tools for scanning.
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v1
      #   id: initialize-codeql
      #   with:
      #     languages: ${{ matrix.language }}
      #     # If you wish to specify custom queries, you can do so here or in a config file.
      #     # By default, queries listed here will override any specified in a config file.
      #     # Prefix the list here with "+" to use these queries and those in the config file.
      #     # queries: ./path/to/local/query, your-org/your-repo/queries@main
      #     queries: "./.github/codeql/specialized-sql-injection.ql"


      # - run: |
      #     ./gradlew testClasses --no-daemon -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000 -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v1

      # - run: |
      #     $CODEQL_DIST/codeql bqrs decode -r allEdges --format=json --output=../results/java-custom.allEdges.json $CODEQL_EXTRACTOR_JAVA_WIP_DATABASE/results/codeql-ccd-data-store-api/specialized-sql-injection.bqrs
      #     cat  ../results/java-custom.allEdges.json
      #     .github/bin/diffblue-security-fix ../results/java-custom.sarif ../results/java-custom.allEdges.json

      - name: Dummy changes
        run: |
          patch -p1 -i .github/smoke-and-mirrors.patch
          sleep 10

      # Creates a new branch name based on the base
      - name: Output new branch name based of the base and head branch
        id: branch-name
        run: |
          NEW_BRANCH="testBranch/${{github.base_ref}}-${{github.head_ref}}"
          echo "Branch name is $NEW_BRANCH"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          echo "::set-output name=branch-name::$NEW_BRANCH"

      - name: Commit and create branch
        run: |
          git branch -D "$NEW_BRANCH" || true
          git push origin --delete "$NEW_BRANCH" || true
          git checkout -b "$NEW_BRANCH"
          git add -A
          git commit -m "Sample commit"
          git push -u origin "$NEW_BRANCH"

      - name: Make pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ steps.branch-name.outputs.branch-name }}"
          destination_branch: "${{github.head_ref}}"
          pr_title: "Fix Security issue"
          pr_body: "This is an automated PR to fix a security issue that we detected was created by your PR"
          github_token: ${{ github.token }}

      # Find PR number
      - name: Find pull request number
        uses: juliangruber/find-pull-request-action@v1.0.2
        id: find-pull-request
        with:
          github-token: ${{ github.token }}
          branch: "${{ steps.branch-name.outputs.branch-name }}"

      - name: Export pull request number
        run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}

      - name: Update comment on PR
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        with:
          message: "Diffblue has detected a vunrability caused by changes in your PR. We have automaticly create a fix for this and create a PR to fix which can be found [HERE](https://github.com/diffblue/ccd-data-store-api/pull/${{ steps.find-pull-request.outputs.number }}) "
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}
