name: Diffblue Security Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  COMMENT_ID: diffblue-test-result-comment-${{github.base_ref}}-${{github.head_ref}}

jobs:
  analyse:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    outputs:
      vulnerability_detected: ${{ steps.analysis.outputs.detected }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Update comment on PR
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        with:
          message: "Diffblue is analysing your PR for security vulnerabilities :hourglass:"
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

      - name: Setup git
        run: |
          git fetch origin
          git checkout ${{ github.head_ref }}

      - name: Pretend to analyse
        id: analysis
        run: |
          sleep 10
          if [ "false" == "true" ]
          then
            echo "No vunrability detected"
            echo "::set-output name=detected::false"
          else
            echo "Something detected"
            echo "::set-output name=detected::true"
            exit 1
          fi

      - name: Comment if Vunrability found
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        if: ${{ failure() }}
        with:
          message: "Diffblue has detected a vunrability caused by changes in your PR. A fix will now be generated :hourglass:"
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

      - name: Comment if Vunrability found
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        if: ${{ success() }}
        with:
          message: "Diffblue has anakysed your pull request and did not find any vunrabilities :heavy_check_mark: "
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

  generate:
    runs-on: ubuntu-latest

    needs: analyse

    if: "always()&&(needs.analyse.outputs.vulnerability_detected=='true')"

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Update comment on PR
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        with:
          message: "Diffblue is generating a fix for your PR"
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

      - name: Setup git
        run: |
          git fetch origin
          git checkout ${{ github.head_ref }}
          git config --global user.email "db-ci-platform@diffblue.com"
          git config --global user.name "Diffblue CI"

      - name: Dummy changes
        run: |
          patch -p1 -i .github/smoke-and-mirrors.patch
          sleep 5

      # Creates a new branch name based on the base
      - name: Output new branch name based of the base and head branch
        id: branch-name
        run: |
          NEW_BRANCH="testBranch/${{github.base_ref}}-${{github.head_ref}}"
          echo "Branch name is $NEW_BRANCH"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          echo "::set-output name=branch-name::$NEW_BRANCH"

      - name: Commit and create branch
        run: |
          git branch -D "$NEW_BRANCH" || true
          git push origin --delete "$NEW_BRANCH" || true
          git checkout -b "$NEW_BRANCH"
          git add -A
          git commit -m "Sample commit"
          git push -u origin "$NEW_BRANCH"

      - name: Make pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ steps.branch-name.outputs.branch-name }}"
          destination_branch: "${{github.head_ref}}"
          pr_title: "Fix Security issue"
          pr_body: "This is an automated PR to fix a security issue that we detected was created by your PR"
          github_token: ${{ github.token }}

      # Find PR number
      - name: Find pull request number
        uses: juliangruber/find-pull-request-action@v1.0.2
        id: find-pull-request
        with:
          github-token: ${{ github.token }}
          branch: "${{ steps.branch-name.outputs.branch-name }}"

      - name: Export pull request number
        run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}

      - name: Update comment on PR
        uses: phulsechinmay/rewritable-pr-comment@v0.2
        with:
          message: "Diffblue has detected a vunrability caused by changes in your PR. We have automaticly create a fix for this and create a PR to fix which can be found [HERE](https://github.com/diffblue/ccd-data-store-api/pull/${{ steps.find-pull-request.outputs.number }}) "
          GITHUB_TOKEN: ${{ github.token }}
          COMMENT_IDENTIFIER: ${{ env.COMMENT_ID }}

